name: Build and Deploy

on:
  workflow_dispatch:

permissions:
  packages: write

env:
  CGO_ENABLED: "0"
  TZ: Asia/Shanghai

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          repository: pmkol/mosdns-x
          ref: main

      - name: get latest go version
        id: go
        run: |
          echo version=$(curl -s https://raw.githubusercontent.com/actions/go-versions/update-versions-manifest-file/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g') >> $GITHUB_OUTPUT

      - name: Set up Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: ${{steps.go.outputs.version}}

      - name: Build
        run: |
          echo "TAG_NAME=v$(date +'%y.%m.%d')" >> "$GITHUB_ENV"
          go build

      - name: Upload binary
        uses: actions/upload-artifact@v4.6.2
        with:
          path: 'mosdns-x'

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3
        id: buildx

      - name: login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: get Dockerfile
        run: |
          curl -skLo Dockerfile https://raw.githubusercontent.com/${{ github.repository }}/main/Dockerfile

      - name: build and publish ghcr.io docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/johnsonran/mosdns-x:latest
